[package]
name = "spiral-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "ntt"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
