[package]
name = "spiral-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { features = ["js"], version = "0.2.6" }
rand = { version = "0.8.5" }
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }
pprof = { version = "0.4", features = ["flamegraph", "criterion"] }

[[bench]]
name = "ntt"
harness = false

[[bench]]
name = "server"
harness = false

[[bench]]
name = "poly"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
