[package]
name = "spiral-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { features = ["js"] }
rand = { version = "0.8.5" }
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "ntt"
harness = false

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
